name: Analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint-app:
    runs-on: ubuntu-20.04
    name: Lint & build app
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Lint app dockerfile
        uses: brpaz/hadolint-action@v1.5.0
        with:
          dockerfile: Dockerfile
      - name: Set up Node.js
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
      - name: Install NPM Packages
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
